sync-database-test-replication-bulk-aarnet-50MB:
    description: "Sync external database with rule information in datalake (test-upload-dev)"
    module_name: "tasks.sync.database"
    class_name: "SyncESDatabase"
    enabled: true
    args:
    kwargs:
      fts_endpoint: https://fts3-pilot.cern.ch:8446
      task_name_to_update: test-replication-bulk-aarnet-50MB 
      n_workers: 6
      update_all: true
      database:
        type: es
        uri: https://srcdev.skatelescope.org/rucio-dev/monit/elastic/
        index: "custom"
        search_range_lte: now
        search_range_gte: now-7d
        max_rows: 10000

sync-database-test-replication-bulk-idia-50MB:
    description: "Sync external database with rule information in datalake (test-upload-replication-dev)"
    module_name: "tasks.sync.database"
    class_name: "SyncESDatabase"
    enabled: true
    args:
    kwargs:
      fts_endpoint: https://fts3-pilot.cern.ch:8446
      task_name_to_update: test-replication-bulk-idia-50MB
      n_workers: 10
      update_all: true
      database:
        type: es
        uri: https://srcdev.skatelescope.org/rucio-dev/monit/elastic/
        index: "custom"
        search_range_lte: now
        search_range_gte: now-7d
        max_rows: 10000

sync-database-test-replication-bulk-aarnet-500MB:
    description: "Sync external database with rule information in datalake (test-upload-dev)"
    module_name: "tasks.sync.database"
    class_name: "SyncESDatabase"
    enabled: true
    args:
    kwargs:
      fts_endpoint: https://fts3-pilot.cern.ch:8446
      task_name_to_update: test-replication-bulk-aarnet-500MB 
      n_workers: 10
      update_all: true
      database:
        type: es
        uri: https://srcdev.skatelescope.org/rucio-dev/monit/elastic/
        index: "custom"
        search_range_lte: now
        search_range_gte: now-7d
        max_rows: 10000

sync-database-test-replication-bulk-idia-500MB:
    description: "Sync external database with rule information in datalake (test-upload-replication-dev)"
    module_name: "tasks.sync.database"
    class_name: "SyncESDatabase"
    enabled: true
    args:
    kwargs:
      fts_endpoint: https://fts3-pilot.cern.ch:8446
      task_name_to_update: test-replication-bulk-idia-500MB
      n_workers: 10
      update_all: true
      database:
        type: es
        uri: https://srcdev.skatelescope.org/rucio-dev/monit/elastic/
        index: "custom"
        search_range_lte: now
        search_range_gte: now-7d
        max_rows: 10000

sync-database-test-replication-bulk-aarnet-5GB:
    description: "Sync external database with rule information in datalake (test-upload-dev)"
    module_name: "tasks.sync.database"
    class_name: "SyncESDatabase"
    enabled: true
    args:
    kwargs:
      fts_endpoint: https://fts3-pilot.cern.ch:8446
      task_name_to_update: test-replication-bulk-aarnet-5GB 
      n_workers: 10
      update_all: true
      database:
        type: es
        uri: https://srcdev.skatelescope.org/rucio-dev/monit/elastic/
        index: "custom"
        search_range_lte: now
        search_range_gte: now-7d
        max_rows: 10000

sync-database-test-replication-bulk-idia-5GB:
    description: "Sync external database with rule information in datalake (test-upload-replication-dev)"
    module_name: "tasks.sync.database"
    class_name: "SyncESDatabase"
    enabled: true
    args:
    kwargs:
      fts_endpoint: https://fts3-pilot.cern.ch:8446
      task_name_to_update: test-replication-bulk-idia-5GB
      n_workers: 10
      update_all: true
      database:
        type: es
        uri: https://srcdev.skatelescope.org/rucio-dev/monit/elastic/
        index: "custom"
        search_range_lte: now
        search_range_gte: now-7d
        max_rows: 10000
