sync-database-test-replication-bulk-idia-50MB:
    description: "Sync external database with rule information in datalake (test-upload-replication-dev)"
    module_name: "tasks.sync.database"
    class_name: "SyncESDatabase"
    enabled: true
    args:
    kwargs:
      fts_endpoint: https://fts3-pilot.cern.ch:8446
      task_name_to_update: test-replication-bulk-idia-50MB
      n_workers: 1
      update_all: true
      database:
        type: es
        uri: https://srcdev.skatelescope.org/rucio-dev/monit/elastic/
        index: "custom"
        search_range_lte: now
        search_range_gte: now-7d
        max_rows: 10000
