FROM registry.gitlab.com/ska-telescope/src/ska-rucio-client 

USER root

RUN yum -y install wget vim python3 git

COPY . /opt/rucio-analysis

WORKDIR /opt/rucio-analysis

RUN python3 -m pip install -r /opt/rucio-analysis/requirements.txt

ENV TASK_FILE_SUBPATH ./etc/tasks/test.stubs.yml

ENTRYPOINT ["./etc/init/docker-init.sh"]