image:
  repository: registry.gitlab.com/ska-telescope/src/ska-rucio-prototype/ska-rucio-analysis-client
  tag: latest
  pullPolicy: Always

deployment:
  namespace: rucio-analysis

config:
  RUCIO_CFG_RUCIO_HOST: https://srcdev.skatelescope.org/rucio-dev
  RUCIO_CFG_AUTH_HOST: https://srcdev.skatelescope.org/rucio-dev
  RUCIO_CFG_ACCOUNT: robbarnsley
  RUCIO_CFG_AUTH_TYPE: oidc
  RUCIO_CFG_USERNAME:
  RUCIO_CFG_PASSWORD:
  VOMS: skatelescope.eu

secrets:
  - name: OIDC_AGENT_AUTH_CLIENT_CFG_VALUE
    fromSecretName: oidc-agent-auth-client
    fromSecretKey: cfg
  - name: OIDC_AGENT_AUTH_CLIENT_CFG_PASSWORD
    fromSecretName: oidc-agent-auth-client
    fromSecretKey: password
  - name: KUBE_CONFIG_VALUE
    fromSecretName: kube
    fromSecretKey: cfg.dev
  - name: RUCIO_CFG_CLIENT_CERT_VALUE
    fromSecretName: rucio-cfg-client
    fromSecretKey: certificate
  - name: RUCIO_CFG_CLIENT_KEY_VALUE
    fromSecretName: rucio-cfg-client
    fromSecretKey: key
  - name: TASK_SYNC_IAM_RUCIO_CLIENT_SECRET
    fromSecretName: task-sync-iam-rucio
    fromSecretKey: client_secret

cronjobs:
  - name: stubs
    minute: "*/15"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    task_file_path: "etc/tasks/stubs.yml"
    disabled: yes
  - name: tests-transfers
    minute: "*/15"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    task_file_path: "etc/tasks/skao-dev/tests/upload-and-replication.yml"
    disabled: yes
  - name: db-sync
    minute: "*/5"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    task_file_path: "etc/tasks/skao-dev/sync/sync-upload-and-replication.yml"
    disabled: yes
  - name: reports-daily
    minute: "0"
    hour: "9"
    day: "*"
    month: "*"
    weekday: "*"
    task_file_path: "etc/tasks/skao-dev/reports/daily.yml"
    disabled: yes
  - name: probes-daemons
    minute: "*/1"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    task_file_path: "etc/tasks/skao-dev/probes/daemons.yml"
    disabled: yes
  - name: probes-service-heartbeats
    minute: "*/1"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    task_file_path: "etc/tasks/skao-dev/probes/service_heartbeats.yml"
    disabled: yes
  - name: probes-service-metrics-fts
    minute: "*/1"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    task_file_relpath: "etc/tasks/skao-dev/probes/service_metrics.yml"
    disabled: yes
  - name: probes-fts
    minute: "*/1"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    task_file_relpath: "etc/tasks/skao-dev/probes/fts.yml"
    disabled: yes
  - name: sync-iam-rucio
    minute: "*/1"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    task_file_yaml:  
      sync-iam-rucio-dev:
        description: Sync IAM users with a Rucio server
        module_name: tasks.sync.iam
        class_name: SyncIAMRucio
        enabled: true
        args:
        kwargs:
          iam_server_base_url: https://iam-escape.cloud.cnaf.infn.it/
          client_id: 5313fe03-ad7f-4094-99af-f93d173cebb4
          client_secret: "{{ TASK_SYNC_IAM_RUCIO_CLIENT_SECRET }}"
          rucio_user_iam_groups:
            - escape/ska
          rucio_admin_iam_groups:
            - escape/ska/admins
          skip_accounts:
            - root
          rse_quota: 1000000000000
          dry_run: False
