image:
  repository: registry.gitlab.com/ska-telescope/src/ska-rucio-prototype/ska-rucio-analysis-client
  tag: latest
  pullPolicy: Always

deployment:
  namespace: rucio-analysis

config:
  RUCIO_CFG_RUCIO_HOST: https://srcdev.skatelescope.org/rucio-dev
  RUCIO_CFG_AUTH_HOST: https://srcdev.skatelescope.org/rucio-dev
  RUCIO_CFG_ACCOUNT: root
  RUCIO_CFG_AUTH_TYPE: oidc

secrets:
  - name: OIDC_AGENT_AUTH_CLIENT_CFG_VALUE
    fromSecretName: oidc-agent-auth-client
    fromSecretKey: cfg
  - name: OIDC_AGENT_AUTH_CLIENT_CFG_PASSWORD
    fromSecretName: oidc-agent-auth-client
    fromSecretKey: password
  - name: TASK_SYNC_IAM_RUCIO_CLIENT_SECRET
    fromSecretName: task-sync-iam-rucio
    fromSecretKey: client_secret

cronjobs:
  - name: sync-iam-rucio-dev
    minute: "*/15"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    task_file_yaml: 
      sync-iam-rucio-dev:
        description: Sync IAM users with a Rucio server
        module_name: tasks.sync.iam
        class_name: SyncIAMRucio
        enabled: true
        args:
        kwargs:
          iam_server_base_url: https://iam-escape.cloud.cnaf.infn.it/
          client_id: 5313fe03-ad7f-4094-99af-f93d173cebb4
          client_secret: "{{ TASK_SYNC_IAM_RUCIO_CLIENT_SECRET }}"
          rucio_user_iam_groups:
            - escape/ska
          rucio_admin_iam_groups:
            - escape/ska/admins
          skip_accounts:
            - root
            - skao-rucio-service-1
          rse_quota: 1000000000000
          dry_run: False
