jobs:
  - name: tests-transfers
    minute: "0"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    task_subpath: "escape/tests/upload-and-replication.yml"
    disabled: no
 
  - name: db-sync
    minute: "*/5"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    task_subpath: "escape/db/sync-upload-and-replication.yml"
    disabled: no
    
  - name: reports-daily
    minute: "0"
    hour: "9"
    day: "*"
    month: "*"
    weekday: "*"
    task_subpath: "escape/reports/daily.yml"
    disabled: no

