jobs:
#  - name: tests-transfers-50MB-dev
#    minute: "35"
#    hour: "0-23/3"
#    day: "27-28"
#    month: "10"
#    weekday: "*"
#    task_subpath: "escape-stress-tests/tests/replication-bulk-50MB.yaml"
#    disabled: no
#
#  - name: tests-transfers-500MB-dev
#    minute: "35"
#    hour: "1-23/3"
#    day: "27-28"
#    month: "10"
#    weekday: "*"
#    task_subpath: "escape-stress-tests/tests/replication-bulk-500MB.yaml"
#    disabled: no
#
#  - name: tests-transfers-5GB-dev
#    minute: "35"
#    hour: "2-23/3"
#    day: "27-28"
#    month: "10"
#    weekday: "*"
#    task_subpath: "escape-stress-tests/tests/replication-bulk-5GB.yaml"
#    disabled: no
#
#  - name: tests-transfers-upload-and-register-dev
#    minute: "0"
#    hour: "*"
#    day: "26"
#    month: "10"
#    weekday: "*"
#    task_subpath: "escape-stress-tests/tests/upload-and-register.yml"

  - name: db-sync-dev
    minute: "*/5"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    task_subpath: "escape-stress-tests/sync/sync-replication-bulk.yml"
    disabled: no

