# Ansible 
# 
---
  - name: "deploy to remote machine"
    hosts: "{{ HOSTS }}"
    roles: 
      - common
    gather_facts: true
    vars_prompt:
    - name: ansible_user
      prompt: Remote machine username?
      default: rbarnsley
      private: no
    - name: ansible_ssh_private_key_file
      prompt: remote machine ssh private key path?
      default: ~/.ssh/id_rsa
      private: no
    - name: copy_credentials
      prompt: Copy x509 credentials?
      default: no
      private: no
    - name: install_dependencies
      prompt: Install rucio-analysis dependencies?
      default: no
      private: no
    - name: install_rucio_analysis
      prompt: Install rucio-analysis?
      default: no
      private: no
    - name: install_crontab
      prompt: Install crontab?
      default: yes
      private: no
    tasks:
    - name: load role vars
      include_vars:
        file: "roles/{{ ansible_role }}/vars/main.yml"
      delegate_to: 127.0.0.1
    - include_role:
        name: common
        tasks_from: check_x509_credentials_set
      when: RUCIO_CFG_AUTH_TYPE == "x509"
    - include_role:
        name: common
        tasks_from: check_userpass_credentials_set
      when: RUCIO_CFG_AUTH_TYPE == "userpass"
    - include_role:
        name: common
        tasks_from: copy_x509_credentials
      when: copy_credentials|bool
    - include_role:
        name: common
        tasks_from: install_dependencies
      when: install_dependencies|bool
    - include_role:
        name: common
        tasks_from: install_rucio_analysis
      when: build_rucio_analysis|bool
    - include_role:
        name: common
        tasks_from: install_crontab
      when: install_crontab|bool
