.ONESHELL:

deploy-to-skao-rucio-analysis:
	ansible-playbook -i hosts/inventory.yml deploy.yml -e HOSTS=skao-rucio-analysis

deploy-to-escape-rucio-analysis:
	ansible-playbook -i hosts/inventory.yml deploy.yml -e HOSTS=escape-rucio-analysis
