# Ansible 
# 
---
  - name: "update local machine"
    hosts: "{{ HOSTS }}"
    connection: local
    roles: 
      - common
    vars_prompt:
    - name: install_dependencies
      prompt: Install rucio-analysis dependencies?
      default: no
      private: no
    - name: install_rucio_analysis_local
      prompt: Install rucio-analysis?
      default: no 
      private: no
    - name: mount_rucio_oidc_admin_token
      prompt: Add cronjob to retrieve rucio oidc admin token and mount into containers?
      default: no
      private: no
    - name: mount_k8s_cluster_config
      prompt: Mount k8s cluster config file into containers? (required by some probes)
      default: no
      private: no
    - name: install_task_crontab
      prompt: Install task crontab?
      default: no
      private: no
    tasks:
    - debug:
        msg: "ansible_role: {{ ansible_role }}"
    - name: load role vars
      include_vars:
        file: "roles/{{ ansible_role }}/vars/main.yml"
      delegate_to: 127.0.0.1
    - include_role:
        name: common
        tasks_from: check_x509_credentials_set
      when: RUCIO_CFG_AUTH_TYPE == "x509"
    - include_role:
        name: common
        tasks_from: check_userpass_credentials_set
      when: RUCIO_CFG_AUTH_TYPE == "userpass"
    - include_role:
        name: common
        tasks_from: install_dependencies
      when: install_dependencies|bool
    - include_role:
        name: common
        tasks_from: install_rucio_analysis_local
      when: install_rucio_analysis_local|bool
    - include_role:
        name: common
        tasks_from: add_cronjob_rucio_oidc_admin_token
      when: mount_rucio_oidc_admin_token|bool
    - include_role:
        name: common
        tasks_from: install_task_crontab
      when: install_task_crontab|bool
