reports:
    description: "Send daily report"
    module_name: "tasks.reports.daily"
    class_name: "ReportDaily"
    enabled: true
    args:
    kwargs:
      database:
        type: es
        uri: http://130.246.214.144:80/monit/metadata/
        index: "[replication]"
        search_range_lte: now
        search_range_gte: now-24h
        max_rows: 10000
      percentage_stuck_warning_threshold: 1
      rses:
        - ALPAMED-DPM
        - CNAF-STORM
        - DESY-DCACHE
        - EULAKE-1
        - GSI-ROOT
        - IN2P3-CC-DCACHE
        - INFN-NA-DPM
        - LAPP-DCACHE
        - PIC-DCACHE
        - SARA-DCACHE
        - LAPP-WEBDAV
      webhooks:
        - type: slack
          url: 
