- name: assert Rucio configuration variables are set for userpass authentication.
  assert: 
    that:
      - RUCIO_CFG_USERNAME is defined
      - RUCIO_CFG_PASSWORD is defined
      - RUCIO_CFG_AUTH_TYPE is defined and RUCIO_CFG_AUTH_TYPE == "userpass"
    fail_msg: "RUCIO_CFG_USERNAME and RUCIO_CFG_PASSWORD must be defined with RUCIO_CFG_AUTH_TYPE set for userpass authentication."