- name: assert Rucio configuration variables are set for x509 authentication.
  assert: 
    that:
      - RUCIO_CFG_ACCOUNT is defined
      - RUCIO_CFG_CLIENT_CERT is defined
      - RUCIO_CFG_CLIENT_KEY is defined
      - RUCIO_CFG_AUTH_TYPE is defined and RUCIO_CFG_AUTH_TYPE == "x509"
    fail_msg: "RUCIO_CFG_ACCOUNT, RUCIO_CFG_CLIENT_CERT and RUCIO_CFG_CLIENT_KEY must be defined with RUCIO_CFG_AUTH_TYPE set for x509 authentication."
