- name: copy x509 credentials to remote machine.
  block: 
    - name: make .globus directory if it doesn't exist
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.globus"
        state: directory
        mode: '0755'
    - name: copy x509 certificate
      ansible.builtin.copy:
        src: "{{ RUCIO_CFG_CLIENT_KEY }}"
        dest: "{{ ansible_env.HOME }}/.globus/client.key"
        mode: '0400'
    - name: copy x509 key
      ansible.builtin.copy:
        src: "{{ RUCIO_CFG_CLIENT_CERT }}"
        dest: "{{ ansible_env.HOME }}/.globus/client.crt"
        mode: '0400'
