- name: copy x509 credentials to remote machine.
  block: 
    - name: make .x509 directory if it doesn't exist
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.x509"
        state: directory
        mode: '0755'
    - name: copy x509 certificate
      ansible.builtin.copy:
        src: "{{ RUCIO_CFG_CLIENT_KEY }}"
        dest: "{{ ansible_env.HOME }}/.x509/{{ RUCIO_CFG_CLIENT_KEY | basename }}"
        mode: '0400'
    - name: copy x509 key
      ansible.builtin.copy:
        src: "{{ RUCIO_CFG_CLIENT_CERT }}"
        dest: "{{ ansible_env.HOME }}/.x509/{{ RUCIO_CFG_CLIENT_CERT | basename }}"
        mode: '0400'
